apiVersion: v2
name: hivebox
version: 1.0.0
description: A Helm chart for the hivebox application
type: application
appVersion: "0.0.2"

# Meta data
keywords:
  - devops
  - api

maintainers:
  - name: Ehab Ashraf
    email: ehabxm25@gmail.com

sources:
  - https://github.com/EhabAshrafMu/devops-hands-on-project-hivebox
