apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use base resources
resources:
- ../../base

# Dev-specific settings
namePrefix: dev-

# Add dev labels
labels:
- includeSelectors: true
  pairs:
    environment: development
